### ISSUE TITLE
Vinyl engine

### ISSUE THREAD

**Issue by blry** [tarantool/document#5]
Hi, I've found out that tarantool crashes when I insert a tuple with a different format.

```lua
-- Tarantool: 1.9.0-52-g38b2a29ff

local profileSpace = box.schema.create_space('profile', {
    engine = 'vinyl'
})

local doc = require("document")

doc.create_index(profileSpace, 'primary', {parts={'oid', 'string'}})
doc.insert(profileSpace, {oid = 'test1'})
doc.insert(profileSpace, {oid = 'test2', email = 'test2@mail'})
```
**Error: Vinyl does not support changing space format of a non-empty space**

**Comment by knazarov** [comment]
@blry try it with Tarantool 1.10. It may just work there, as we've added changing space format on the fly
